language: python

matrix:
  include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: "3.6.6"
          dist: trusty

install:
  - python --version
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  # command to install dependencies
  - pip install -e .

script:
  # for codecov support
  - pip install pytest pytest-cov
  # to report installed packages
  - pip freeze
  # command to run tests
  - python setup.py test
#  - pytest --cov-config .coveragerc --cov=./ tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)
